# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ac3b2b76bd24342d4bc6ecbbe15f84957d22b63249c0ab02da4951755188f0eb7b423ae2c847441866c4e65b0f5d555af2b7d35d65947ce31a68bdc55e41afa

test:
  secret_key_base: e7892b4881c10cf4c15e99f960c7f37e77ac22fdba2c1b55b7fb98f5afca95a89b7c0cb3898bd300d56fdb120da3ad480f7cd5390789c2f4ef66f2c23d87ad0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
